DefaultExcludePatterns should only be used for specified linter
golangci/golangci-lint pull request #1494
Opened 2020-11-06 07:25 UTC by ZYunH

Fixes https://github.com/golangci/golangci-lint/issues/1474

This PR add "EXC0011", because most of package in golangci-lint does not having a package comment. `make test` passed.

2020-11-06 07:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golangci/golangci-lint?pullRequest=1494) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golangci/golangci-lint?pullRequest=1494) before we can accept your contribution.<br/><hr/>**zhangyunhao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golangci/golangci-lint?pullRequest=1494) it.</sub>

2020-11-06 07:33 UTC, ZYunH commented
CI has failed, because 
```
Error: directive `// nolint:dupl,stylecheck` is unused for linter stylecheck (nolintlint)
Error: directive `// nolint:dupl,stylecheck` is unused for linter stylecheck (nolintlint)
```

If these two lines removed, the local test will be failed, output
```
pkg/golinters/gocognit.go:1:1: ST1000: package comment should be of the form "Package golinters ..." (stylecheck)
// nolint:dupl
^
pkg/golinters/gocyclo.go:1:1: ST1000: package comment should be of the form "Package golinters ..." (stylecheck)
// nolint:dupl
^
```

maybe something wrong in `stylecheck`? since even having a package comment in `pkg/golinters/asciicheck.go`,  the test still failed, and the output is same as above.

2020-11-07 21:19 UTC, iwankgb commented
I think that what you are doing here (changing semantics of an existing flag) is not a good idea. I would rather expect new flag to be introduced and handle the new case. Adding `// nolint:stylecheck` in quite a few places seems to be a prove that this change is not backward compatible and in the same time it does not seem to be a bug fix.

2020-11-08 03:44 UTC, ZYunH commented
The `// nolint:stylecheck` is added because `// nolint:dupl` is not a valid package comment, and makes the test failed(even add a package comment in `package golinters`). This problem will be fixed if https://github.com/dominikh/go-tools/pull/871 is merged, then we can remove these `// nolint:stylecheck`, and add a valid package comment to `package golinters`.

2020-11-08 06:04 UTC, ZYunH commented
@iwankgb we can keep backward compatible by adding a new rule like 
```
	{
		ID: "EXC0012",
		Pattern: "(comment on exported (method|function|type|const)|" +
			"should have( a package)? comment|comment should be of the form)",
		Linter: "stylecheck",
		Why:    "Annoying issue about not having a comment. The rare codebase has such comments",
	},
```
Then we can remove all these `// nolint:stylecheck`. But i don't know which is better, maybe someone from the team can give some ideas @golangci-releaser

2020-11-08 06:52 UTC, ZYunH commented
After put some thought to it, i think keeping backward compatible makes this PR more easily to understand, but it cover some mistakes in testdata and stylecheck.

2020-11-08 21:57 UTC, iwankgb commented
@ZYunH now I understand what you mean. I believe that your PR and issue are basically a bugfix and bugreport. If we provide linter information then we should not apply default exclude rules to all the linters. Taking above into consideration I have only one request: provide tests for `GetExcludePatterns()` and exclude processor use-case.
First test should be pretty straightforward. In case of the second one you will have to dig into [testdata directory](https://github.com/golangci/golangci-lint/tree/master/test/testdata) and prepare a file with matching violations that would fail on master and pass on your branch. Let me know if you have any issues, I will try to help :)

2020-11-09 07:05 UTC, ZYunH commented
@iwankgb PTAL, thanks!

2020-11-11 17:45 UTC, iwankgb requested changes
This is last final piece of change and I will be more than happy to merge the PR.

2020-11-11 17:45 UTC, iwankgb commented on pkg/config/config_test.go
> +		if !inDefaultExc {
I would rather use `assert.True()`

2020-11-12 03:56 UTC, ZYunH commented on pkg/config/config_test.go
> +		if !inDefaultExc {
Done

2020-11-12 14:20 UTC, iwankgb approved these changes

2020-11-12 14:21 UTC, merged