Add setttings examples for gocritic
golangci/golangci-lint pull request #1562
Opened 2020-12-17 16:27 UTC by sebastien-rosset

Add gocritic settings in the example file.

2020-12-17 16:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golangci/golangci-lint?pullRequest=1562) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golangci/golangci-lint?pullRequest=1562) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golangci/golangci-lint?pullRequest=1562) it.</sub>

2020-12-17 23:16 UTC, quasilyte approved these changes

2020-12-18 04:42 UTC, butuzov approved these changes

2020-12-18 06:29 UTC, ldez requested changes
I think it's better to reference the documentation instead of the gocritic command line.

2020-12-18 06:29 UTC, ldez commented on .golangci.example.yml
> +    # The list of supported checker settings can be obtained using `gocritic check -h`
```suggestion
    # The list of supported checkers can be find in https://go-critic.github.io/overview.
```

2020-12-18 10:05 UTC, ldez approved these changes
Thanks :+1:

2020-12-18 10:35 UTC, merged