Add forbidigo linter
golangci/golangci-lint pull request #1569
Opened 2020-12-21 14:52 UTC by ashanbrown

Forbidigo forbids identifiers.  It can be used to forbid code that is useful for debugging but should not be merged to the master branch.  I've found it particularly useful to make sure I don't commit `fmt.Print.*` statements or `ginkgo.F.*` commands that I've introduced during local debugging.

2020-12-24 15:30 UTC, ldez requested changes
Could you also run a `go mod tidy`?

Thank you.

2020-12-24 15:30 UTC, ldez commented on pkg/golinters/forbidigo.go
> +			for _, file := range pass.Files {
```suggestion
			linter, err := forbidigo.NewLinter(s.Forbid)
			if err != nil {
				return nil, errors.Wrapf(err, "failed to create linter %q", forbidigoName)
			}
			
			var res []goanalysis.Issue
			for _, file := range pass.Files {
```

2020-12-24 15:30 UTC, ldez commented on pkg/golinters/forbidigo.go
> +			linter, err := forbidigo.NewLinter(s.Forbid)
Could you rename `linter` to `forbid` to avoid that the variable 'linter' collides with the imported package name?

2020-12-24 16:00 UTC, ashanbrown commented
Should we be verifying that `go mod tidy` produces no changes in CI?  Also, I'm wondering if we should consider linter checks for the other items you mentioned (whitespace and shadowed imports).

2020-12-24 16:09 UTC, ldez commented
@ashanbrown there was an RP to change this behavior #1397. I think that this PR can be revert since dependabot is now able to manage `go.sum` file.

2020-12-24 16:10 UTC, ldez approved these changes
LGTM

2020-12-24 16:19 UTC, merged

2020-12-28 23:07 UTC, davidnewhall commented on pkg/golinters/forbidigo.go
> +						FromLinter: makezeroName,
THIS IS A BUG.

2020-12-28 23:12 UTC, SVilgelm commented on pkg/golinters/forbidigo.go
> +						FromLinter: makezeroName,
It's already fixed in #1590