Allow multiple linters to be removed from nolint statement by nolint …
golangci/golangci-lint pull request #1583
Opened 2020-12-27 18:31 UTC by ashanbrown

…fixer

Also ensure that //nolint:nolintlint can be used to disable nolintlint

2020-12-27 18:32 UTC, ashanbrown commented on test/testdata/fix/in/nolintlint.go
> +	fmt.Println() // nolint:bob // leading space should be dropped
just changed this to something that doesn't trigger other linter errors

2020-12-27 18:39 UTC, ldez commented
@ashanbrown could you reference the issue(s)? 

https://github.com/golangci/golangci-lint/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+nolintlint

Have you seen https://github.com/golangci/golangci-lint/pull/1573#issuecomment-751480996 ?

2020-12-27 18:57 UTC, ashanbrown commented
@ldez This ended up involving some relatively larger changes than anticipated and might take some time to review, so if you'd prefer that we revert #1573 and roll it together with this, I can put up a PR to do that.

My understanding of the issues with #1573 is that it would potentially lead to bad fixes for issues that already existed, which seems unlikely to adversely affect many (if any) users.

2020-12-27 18:58 UTC, ashanbrown commented on pkg/result/processors/nolint.go
> +	// only allow selective nolinting of nolintlint
This has been reorganized so that we can do `//nolint:nolintlint` to disable `nolintlint` checking.

2020-12-27 19:30 UTC, ldez commented
> One thing this PR does not do is to remove empty linter lists (such as ,,) or trailing , from a list of linters. I'll put that in a subsequent PR.

> This ended up involving some relatively larger changes than anticipated and might take some time to review, so if you'd prefer that we revert #1573 and roll it together with this, I can put up a PR to do that.

I would prefer to revert #1573 and create one PR with all the elements related to the feature.

2020-12-27 19:56 UTC, ashanbrown commented on pkg/result/processors/nolint.go
> -		if !i.ExpectNoLint {
Now we are allowing nolint directives to be excluded by `//nolint:nolintlint`.

2020-12-31 16:10 UTC, ashanbrown commented
@ldez I would love it if you could take a look at this re-attempt to add a `//nolint` fixer.  I believe it addresses all the issues you pointed out with the original fixer.  Thank you.

2021-01-07 23:12 UTC, ldez requested changes
I confirm that #1579, #1580, #1581 are fixes.

---

### Trailing comma after the fix

<details>
<summary>one unused linter (begin) [OK]</summary>

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:gocyclo,nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

</details>

<details>
<summary>one unused linter (end) [KO]</summary>

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:nakedret,gocyclo
func wantedErrors(file, short string) (errs []wantedError) {
```

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:nakedret,
func wantedErrors(file, short string) (errs []wantedError) {
```

</details>

<details>
<summary>two unused linter (begin) [OK]</summary>

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:gocyclo,dupl,nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

</details>

<details>
<summary>two unused linter (end) [KO]</summary>

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:gocyclo,dupl,nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:nakedret,
func wantedErrors(file, short string) (errs []wantedError) {
```

</details>

### Trailing two dot after the fix

<details>
<summary>only unused linters [KO]</summary>

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:gocyclo,dupl
func wantedErrors(file, short string) (errs []wantedError) {
```

```go
// wantedErrors parses expected errors from comments in a file.
//nolint:
func wantedErrors(file, short string) (errs []wantedError) {
```

```
test/errchk.go:163:1: directive `//nolint:` should match `//nolint:[:<comma-separated-linters>] [// <explanation>]` (nolintlint)
//nolint:
^
```

</details>

---

The fact to not have a homogeneous behavior depending on the position of the used linter is not expected for me.

In some cases (ex: only unused linters), the auto-fix produces an error

I think that the trailing commas must handle by this PR.

Also when the auto-fix will produce an empty `//nolint:`, I think that the fix must not be applied, and `Replacement{NeedOnlyDelete: true}` can be better here.

2021-01-11 01:08 UTC, ashanbrown commented
@ldez Thanks for looking at this more.  I'm concerned trying to completely cleanly handle the cases with multiple linters specified with `//nolint` will make this PR significantly more complicated and I'd prefer to handle that case in a subsequent PR.  I think these issues could be fixed up by hand after running fix.  The `nolintlint` linter itself will catch the failing cases, preventing them from being committed.  I believe that, due to the possibility of conflicting fixes between different linters, we do not guarantee that "fix" always fixes everything.  If leaving the cases you mention as TODO is ok with you, I'd prefer to merge this as is.  Note that I did this work during my xmas break and I likely won't have more time to spend on this for a few weeks.  That said, if you'd care to try to address those issues before merging, please feel welcome.  I'd be happy to review your changes.

2021-02-20 22:07 UTC, ldez commented
@ashanbrown could you clean a bit your PR? I think you made a wrong rebase :wink:

2021-02-20 22:08 UTC, ldez requested changes
@ashanbrown could you clean a bit your PR? I think you made a wrong rebase :wink:

2021-02-20 22:21 UTC, ashanbrown commented
@ldez I think I've fixed it up.  The one change since last time is to just skip trying to fix unused linter issues for directives with multiple linters specified.

2021-02-27 14:31 UTC, ashanbrown commented
@ldez Tests are passing now.  I hadn't fixed them correctly after merging the latest code and needed to add another `expected_linter` field.

2021-03-13 03:51 UTC, ldez approved these changes
To clarify the scope of the PR because the scope of the PR has changed since it was open: this PR only fixes the cases where only one linter is defined in the `nolintlint` directive and this only one linter is unused.

2021-03-13 04:11 UTC, merged