Update Wrapcheck to v2.3
golangci/golangci-lint pull request #2145
Opened 2021-07-31 11:01 UTC by hn8

Updat ignoreSigs default, add ignorePackageGlobs

2021-07-31 11:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2145) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golangci/golangci-lint?pullRequest=2145) it.</sub>

2021-07-31 21:48 UTC, ldez requested changes
Hello,

the file `.golangci.example.yml` doesn't describe the default values but it provides an example of the linter's configuration.

2021-07-31 21:48 UTC, ldez commented on .golangci.example.yml
> +    ignorePackageGlobs: []
```suggestion
    ignorePackageGlobs:
        - encoding/*
        - github.com/pkg/*
```

2021-08-02 06:57 UTC, ldez approved these changes
LGTM

2021-08-02 12:15 UTC, tomarrell commented
Thanks a bunch for sorting this.

2021-08-02 12:15 UTC, tomarrell approved these changes

2021-08-02 12:17 UTC, merged