Add govarpkg linter
golangci/golangci-lint pull request #2274
Opened 2021-10-04 19:26 UTC by alexal

Finds variables that collide with imported package names. Inspired by built-in linter in IntelliJ.

2021-10-04 19:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2274) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2274) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golangci/golangci-lint?pullRequest=2274) it.</sub>

2021-10-04 21:56 UTC, ldez requested changes

2021-10-04 21:56 UTC, ldez commented on pkg/lint/lintersdb/manager.go
> +			WithLoadForGoAnalysis().
```suggestion
```

2021-10-04 21:56 UTC, ldez commented on test/testdata/govarpkg.go
> +}
```suggestion
//args: -Egovarpkg
package testdata

import (
	"fmt"
	"strings"
)

func govarpkg() {
	a := []string{"a", "b", "c"}

	strings := strings.Join(a, ",") // ERROR `Variable 'strings' collides with imported package name`
	fmt.Println(strings)
}

```

2021-10-05 06:28 UTC, butuzov commented
Isn't this covered by `importShadow` by [importShadow_](https://github.com/go-critic/go-critic/blob/f599c814bd8d49e04e1ba5d1ced26782127e42f5/checkers/importShadow_checker.go)

2021-10-05 08:08 UTC, ldez commented
Good catch @butuzov, I have looking for this rule but I didn't find it.

https://go-critic.github.io/overview#importShadow-ref

We will close the PR as it's a duplicate.

2021-10-05 08:08 UTC, closed without merging