Replace ioutil with io and os
golangci/golangci-lint pull request #2318
Opened 2021-10-31 05:21 UTC by ahrtr

The ioutil package has already been deprecated in golang 1.16, please see [go1.16#ioutil](https://golang.org/doc/go1.16#ioutil). So we need to replace all the ioutil with os and io.

The ioutil used in yaml or txt files are not updated in this PR.

2021-10-31 05:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2318) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2318) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golangci/golangci-lint?pullRequest=2318) it.</sub>

2021-10-31 10:45 UTC, bombsimon approved these changes
Thanks! LGTM

2021-10-31 13:26 UTC, ldez requested changes
I just want to be precise: the `ioutil` package is not really deprecated, there is no depreciation defined in this package.

The Go team recommends using the new implementation in the new code, but they don't recommend removing it from the existing code (they say nothing about existing code).

> ... we encourage new code to use the new definitions in the io and os packages. 
https://golang.org/doc/go1.16#ioutil

---

For me, the code in the `testdata` package must keep, at least for now, the use of `ioutil`.

2021-10-31 14:27 UTC, bombsimon commented
What do you mean, the linked titel literally says "Deprecation of ioutil"? However, what deprecated means may vary, it's nothing guaranteeing deprecated tools to stop working.

Russ Cox explains this [on twitter](https://twitter.com/_rsc/status/1351676094664110082):
> Seeing discussion of io/ioutil deprecation in various places. 
>
> To be clear: in Go, “deprecated” means only “there is a better, preferred way.” It does not mean “will break in the future.”
>
> Today’s programs using ioutil.ReadFile and friends will keep working forever. 

I see no reason not to use the "better, preferred way" just because Go guarantees it won't stop working.

> For me, the code in the `testdata` package must keep, at least for now, the use of `ioutil`.

Do you mind elaborate on why this is a must for you?

2021-10-31 14:44 UTC, ldez commented
> What do you mean

I mean there are literally no depreciation comments in the package `ioutil`.

It was just to be clear about the real context of this PR.

> Do you mind elaborate on why this is a must for you?

As the package `ioutil` will still be here, I think it's a good idea to keep some tests that use this package.

FYI the CI fails because of changes in the `testdata` packages

2021-10-31 14:55 UTC, bombsimon commented
> As the package ioutil will still be here, I think it's a good idea to keep some tests that use this package.

Thanks for explaining. I was under the impression that it wouldn't still be here but maybe you mean in general in the Go ecosystem.

> FYI the CI fails because of the changes in the testdata package.

Yeah I didn't dig into the root cause but surely there must be a way to make testdata work without `iotuil` I hope.

But if this isn't something that should change in `golangci-lint` I think it makes more sense to close this PR and keep the usage in testdata. If we want to make this change in the future it's probably easier to just file a new PR. WDYT?

2021-10-31 15:12 UTC, ldez commented
> I was under the impression that it wouldn't still be here but maybe you mean in general in the Go ecosystem.

Yes, it will still be in Go code base and Go libraries.

> Yeah I didn't dig into the root cause but surely there must be a way to make testdata work without iotuil I hope.

the `testdata` package contains files used to test the linters. The goal of those files is to evaluate linters, then they always "work".

> But if this isn't something that should change in golangci-lint I think it makes more sense to close this PR and keep the usage in testdata. If we want to make this change in the future it's probably easier to just file a new PR. WDYT?

It's not what I'm trying to say.

There are a few weeks we dropped go1.15 constraints in the CI (2021-10-17) and updated the minimal requirement to go1.16 (2021-10-20 https://github.com/golangci/golangci-lint/pull/2041#issuecomment-948004450).

Yes, now we can use the `ioutil` package replacements through the `io` and `os` package.

The linters are here to evaluate all the Go code even `ioutil` related code, and some tests are here only for this package (ex: `func TestErrcheckIgnoreIoutil()`)

So my opinion is to remove `ioutil` from the golangci-lint code but not in the existing linter test files.

2021-10-31 22:38 UTC, ahrtr commented
Thanks. I just reverted all changes in testdata package.

2021-11-01 19:20 UTC, ldez approved these changes
LGTM

2021-11-01 19:21 UTC, merged