Add errchkjson linter (alternative to #2349)
golangci/golangci-lint pull request #2362
Opened 2021-11-16 21:09 UTC by breml

After the discussion on #2349, in particular in comment https://github.com/golangci/golangci-lint/pull/2349#discussion_r748742253, I decided to submit an alternative PR for the inclusion of _errchkjson_.

In this implementation there is by default no overlap with other linters (in particular _errcheck_ and _staticcheck_). By setting the respective configuration for _errchkjson_, the user can opt-in for the check for "error free json encoding". If the user decides to do so, it is recommended to exclude some functions from being checked by _errcheck_. The necessary instructions are provided to the user as comment in `.golangci.example.yml`.

2021-11-23 19:56 UTC, ldez requested changes

2021-11-23 20:15 UTC, ldez requested changes

2021-11-23 20:15 UTC, ldez commented on .golangci.example.yml
> +
can you move this section to the right position following the alphabetical order?
And add a description of your linter.

2021-11-23 20:15 UTC, ldez commented on pkg/lint/lintersdb/manager.go
> +			WithPresets(linter.PresetBugs, linter.PresetUnused).
```suggestion
			WithPresets(linter.PresetBugs).
```

2021-11-23 20:51 UTC, breml commented
@ldez I applied your review findings, fixed the gofmt issue and I rebased to master. The pipeline is now green.

2021-11-24 00:14 UTC, ldez commented
Can you revert your last commit (85900c3)? It's not related to the CI problem of your PR.

2021-11-24 08:08 UTC, breml commented
> Can you revert your last commit ([85900c3](https://github.com/golangci/golangci-lint/commit/85900c3fa4238adc4c895b324cefd7412db4e173))? It's not related to the CI problem of your PR.

Done

2021-11-26 21:09 UTC, breml commented
All review findings are resolved, all pipelines are green. Is there anything missing?

2021-11-26 22:25 UTC, ldez approved these changes
LGTM

2021-11-26 22:25 UTC, merged