Print error text in <failure> tag content for more readable junit report
golangci/golangci-lint pull request #2460
Opened 2022-01-04 10:15 UTC by byrnedo

Just adds the actual lint error text that is currently only in the `message` attribute, into the content of the `<failure>` tag.
Fixes https://github.com/golangci/golangci-lint/issues/2452

2022-01-04 10:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2460) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2460) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golangci/golangci-lint?pullRequest=2460) it.</sub>

2022-01-04 17:55 UTC, ldez requested changes
The page [here](https://www.ibm.com/docs/en/developer-for-zos/14.1.0?topic=formats-junit-xml-format) provides an example:
```xml
<?xml version="1.0" encoding="UTF-8" ?> 
   <testsuites id="20140612_170519" name="New_configuration (14/06/12 17:05:19)" tests="225" failures="1262" time="0.001">
      <testsuite id="codereview.cobol.analysisProvider" name="COBOL Code Review" tests="45" failures="17" time="0.001">
         <testcase id="codereview.cobol.rules.ProgramIdRule" name="Use a program name that matches the source file name" time="0.001">
            <failure message="PROGRAM.cbl:2 Use a program name that matches the source file name" type="WARNING">
WARNING: Use a program name that matches the source file name
Category: COBOL Code Review – Naming Conventions
File: /project/PROGRAM.cbl
Line: 2
      </failure>
    </testcase>
  </testsuite>
</testsuites>
```

the struct `failureXML` must be changed like that:

```go
type failureXML struct {
	Message string `xml:"message,attr"`
	Type    string `xml:"type,attr"`
	Content string `xml:",cdata"`
}
```

2022-01-04 17:55 UTC, ldez commented on pkg/printers/junitxml.go
> +				Content: i.Pos.String() + ": " + i.Text + "\n" + strings.Join(i.SourceLines, "\n"),
```suggestion
				Type:    i.Severity,
				Message: i.Pos.String() + ": " + i.Text,
				Content: fmt.Sprintf("%s: %s\nCategory: %s\nFile: %s\nLine: %d\nDetails: %s",
					i.Severity, i.Text, i.FromLinter, i.Pos.Filename, i.Pos.Line, strings.Join(i.SourceLines, "\n")),
```

2022-01-05 07:12 UTC, byrnedo commented on pkg/printers/junitxml.go
> +				Content: i.Pos.String() + ": " + i.Text + "\n" + strings.Join(i.SourceLines, "\n"),
@ldez That's done now, pushed

2022-01-05 08:17 UTC, ldez approved these changes

2022-01-05 08:17 UTC, merged

2022-01-05 09:01 UTC, byrnedo commented
@ldez any idea when this will get released?