Add querycheck linter
golangci/golangci-lint pull request #2677
Opened 2022-03-22 15:51 UTC by lufeee

querycheck is a linter that detects query at database/sql package Query function.
in detail, please check following link.
https://github.com/lufeee/execinquery

2022-03-22 16:30 UTC, sivchari commented on pkg/lint/lintersdb/manager.go
> +			WithSince("1.0.0").
```suggestion
			WithSince("1.46.0").
```

2022-03-22 16:30 UTC, sivchari commented on test/testdata/querycheck.go
> +	_, err = db.Query("Update * FROM hoge where id = ?", test) // ERROR "Query not `SELECT` query"
Please add more test case. (e.g. QueryContext, Execute, ExecuteContext).

2022-03-22 16:34 UTC, sivchari commented
Thanks for contributing. I commented nits.

2022-03-23 01:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2677) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golangci/golangci-lint?pullRequest=2677) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golangci/golangci-lint?pullRequest=2677) it.</sub>

2022-03-27 12:56 UTC, ldez commented
Could you rebase your PR? Thanks.

2022-03-27 23:23 UTC, lufeee commented
Sorry, I don't get the meaning.
rebase means squash the all commit, isn't it?

2022-03-27 23:29 UTC, ldez commented
> Sorry, I don't get the meaning.

can you rebase your branch (related to your Pull Request) on the branch `master` of golangci-lint?

> rebase means squash the all commit, isn't it?

nope, rebase means just [rebase](https://git-scm.com/docs/git-rebase)

example:

```
git rebase upstream/master
```

2022-03-27 23:31 UTC, lufeee commented
Thanks, i got it.

2022-03-29 01:37 UTC, ldez commented
I will rebase your branch because I feel that you need help.

2022-03-29 01:51 UTC, ldez commented
Your tag (v1.0) is not valid from the point of view of Go, can you create a valid tag (v1.0.0)?

2022-03-29 05:19 UTC, lufeee commented
Thanks a lot!

2022-03-29 05:29 UTC, lufeee commented
I added new 'v1.0.0' tag and Fix analyzer name

2022-03-29 06:26 UTC, sivchari commented
Can you update go modules ? Because this PR has used incorrect tag version's linter, yet.

2022-03-29 06:28 UTC, sivchari commented on go.mod
>  	github.com/leonklingele/grouper v1.1.0
Please replace v0.0.0-20220322150457-8f5c1333d66e to v1.0.0.

2022-03-29 08:03 UTC, ldez commented
For your information:
- to update the go.sum: `go mod tidy`
- a direct dependency must not be flagged as indirect.

2022-03-29 08:05 UTC, lufeee commented
> For your information:
> 
> * to update the go.sum: `go mod tidy`
> * a direct dependency must not be flagged as indirect.

Thanks for sharing your best solution about dependence.

2022-03-29 08:11 UTC, sivchari approved these changes
LGTM

2022-03-29 08:22 UTC, sivchari requested changes
Sorry, one nits.

2022-03-29 08:22 UTC, sivchari commented on pkg/golinters/execinquery.go
> +	a.Name = linterName // TODO the name must change inside the linter.
```suggestion
	a.Name = linterName
```

2022-03-29 09:24 UTC, sivchari commented
Thanks @ldez .
LGTM

2022-03-29 09:24 UTC, sivchari approved these changes

2022-03-29 10:31 UTC, merged