Add linters description
golangci/golangci-lint pull request #3945
Opened 2023-07-09 21:06 UTC by AlduLonghi

## What?

resolves #3927 

The idea was to add the description for each linter before the snippet in the /linters section.

**Additional**
I added a formatting function that normalizes all linters' descriptions. This function uppercases the first letter and adds a final dot if missing.

## Why?

This is for better understanding so the user doesn't have to scroll all the way up to read the linter's description.

## How?

I call the function GetAllSupportedLinterConfigs() and create a map with each linter's name and description. This way I decrease the complexity since I use just one loop to make it and the later search is O(1).

## Testing?

Everything is working fine.

## Screenshots (optional)

From this:
![Captura de pantalla 2023-07-09 175357](https://github.com/golangci/golangci-lint/assets/60699220/e840dfd4-0d6d-4862-95b8-4d5b6ccf1203)

To this: 
![Captura de pantalla 2023-07-09 175328](https://github.com/golangci/golangci-lint/assets/60699220/ef0e4670-1701-4d9c-9184-cff9f4cc9ac0)

**Additional**

From this:
![Captura de pantalla 2023-07-09 175236](https://github.com/golangci/golangci-lint/assets/60699220/c8253c46-7c83-4015-9ea0-4af7a4e2c598)

To this:
![Captura de pantalla 2023-07-09 175216](https://github.com/golangci/golangci-lint/assets/60699220/6c774bc1-347b-4570-bc8c-9e09d406001b)

Looking forward to your comments :)

2023-07-09 21:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golangci/golangci-lint?pullRequest=3945) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golangci/golangci-lint?pullRequest=3945) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golangci/golangci-lint?pullRequest=3945) it.</sub>

2023-07-10 01:16 UTC, ldez requested changes

2023-07-10 01:16 UTC, ldez commented on scripts/expand_website_templates/main.go
> +	return capitalizeAndAddFinalDot(strings.ReplaceAll(desc, "\n", "<br/>"))
```suggestion
	return formatDesc(desc)
```

2023-07-10 01:16 UTC, ldez commented on scripts/expand_website_templates/main.go
> +}
```suggestion
func formatDesc(desc string) string {
	runes := []rune(desc)
	runes[0] = unicode.ToUpper(rune(desc[0]))

	if runes[len(runes)-1] != '.' {
		runes = append(runes, '.')
	}

	return strings.ReplaceAll(string(runes), "\n", "<br/>")
}
```

2023-07-10 12:44 UTC, AlduLonghi commented on scripts/expand_website_templates/main.go
> +	"gopkg.in/yaml.v3"
Done

2023-07-10 12:45 UTC, AlduLonghi commented on scripts/expand_website_templates/main.go
> +	return capitalizeAndAddFinalDot(strings.ReplaceAll(desc, "\n", "<br/>"))
Done

2023-07-10 12:45 UTC, AlduLonghi commented on scripts/expand_website_templates/main.go
> +}
Done

2023-07-11 08:50 UTC, ldez approved these changes
Hello,

Thank you for your contribution to our project.
Your PR will benefit many users.

I watched your profile and you seem to have frontend knowledge, we have currently a problem with gatsby in the documentation build (#3864, #3934), can you help us with that?

2023-07-11 12:03 UTC, AlduLonghi commented
Hey @ldez! Thank you.

I do have frontend knowledge but I actually never worked with Gatsby before. But let me take a look at the issues and I'll see what I can do about them :)

2023-07-11 13:46 UTC, merged

2023-07-21 13:20 UTC, ldez commented
@AlduLonghi have you taken a look? Can you help us?

If you cannot it's not a problem, I'm just trying to use the opportunity :smiley_cat:.

2023-07-21 13:33 UTC, AlduLonghi commented
Hi @ldez! I've been exploring it the past week and it has to do with Gatsby Migration from v4 to v5. There are some plugins that are not migrated to their latest versions (some needed to be migrated during gatsby migration v3 - v4) and they need code refactoring to function correctly. Is this just this rabbit hole of migrating everything and checking everything works correctly. I might be able to take this next week if that's ok :)