Feat: add `testifylint` linter
golangci/golangci-lint pull request #4072
Opened 2023-09-07 17:05 UTC by Antonboom

Hi!

https://github.com/Antonboom/testifylint

1. Supports `analysis.SuggestedFix` (but no integration in `golangci-lint`?)
2. Supports `analysis.Diagnostic.Category` & `URL` (but no usage of this feature in `golangci-lint`?)

P.S. For local dev you need `1.21`, but the module itself I returned to `1.20` by replacing useful package (`slices`) with own code 😢

2023-09-07 17:07 UTC, ldez commented
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

- [ ] The CLA must be signed

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description of the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license (AGPL is not allowed) and the file must contain the required information by the license, ex: author, year, etc.
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`.
- [ ] It must not contain `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not modify the AST.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.reference.yml`

- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `Manager.GetAllSupportedLinterConfigs(...)` and `.golangci.reference.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
    - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `Manager.GetAllSupportedLinterConfigs(...)`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.
- [ ] `WithURL()` must contain the URL of the repository.

### Recommendations

- [ ] The linter should not use SSA. (SSA can be a problem with generics)
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

The code review will start after the completion of those checkboxes (except for the specific items that the team will help to verify).

If the author of the PR is a member of the golangci-lint team, he should not edit this message.

**This checklist does not imply that we will accept the linter.**

2023-09-19 10:00 UTC, alexandear approved these changes

2023-09-19 10:07 UTC, Antonboom commented on pkg/result/processors/autogenerated_exclude_test.go
> +	require.NoError(t, err)
@alexandear, thank u for review.

> It's good to have assert here

Why? I have no see difference in case of singe-assertion test.

2023-09-20 08:32 UTC, knight42 reviewed
👀 just looking forward to the launch of `testifylint`

2023-09-20 19:25 UTC, ldez requested changes
Your linter contains `panic` and `init` (and the worst `panic` inside `init`)
Can you revert everything not related to the implementation of your linter (the other changes must be pushed inside another PR)?
The default value of the option `enable` must documented like the other linter (inside a comment)
The test file `test/testdata/testifylint_test.go` should be renamed to `test/testdata/testifylint.go`.
The presets should be only `linter.PresetTest` and `linter.PresetBugs`.
The linter should be added inside `enable` and `disable` section.

2023-09-20 19:52 UTC, Antonboom commented
> Your linter contains panic and init (and the worst panic inside init)

This is a nice practice if done wisely. My `init` has no side effects and `panic` reflects the _programming_ error, without which the linter will not start correctly. All cases covered by tests:

```go
return fmt.Errorf("checker with empty name: %T", checker)
return fmt.Errorf("not uniq checker name: %v", name)
```

Examples in other linters:

- https://github.com/go-critic/go-critic/blob/4e433512a8884676ec7e99bb587e2e012eef41a0/checkers/builtinShadow_checker.go#L10
- https://github.com/securego/gosec/blob/293d8875250eebfe61d3ea68c817501d1f525d2a/cwe/data.go#L140
- https://github.com/dominikh/go-tools/blob/4ec1f474ca6c0feb8e10a8fcca4ab95f5b5b9881/stylecheck/lint.go#L756

etc.

> Can you revert everything not related to the implementation of your linter (the other changes must be pushed inside another PR)?

Sure.

> The presets should be only linter.PresetTest and linter.PresetBugs.

Not problem, but just for clarification – why the linter doesn't cover `PresetStyle` and `PresetMetaLinter`?
I was guided by the comments to the constants.

> The test file test/testdata/testifylint_test.go should be renamed to test/testdata/testifylint.go.

In this case, the tests will not work because the linter ignores non-test files for performance and sanity reasons.

> The linter should be added inside enable and disable section.

Sure.

2023-09-20 20:32 UTC, ldez commented
> My init has no side effects and panic reflects the programming error, without which the linter will not start correctly.

This is exactly why we created this rule.
Can you remove them?

2023-09-24 05:39 UTC, closed without merging

2023-09-24 06:07 UTC, Antonboom commented
@ldez, fixed 👌 

Could you please reopen the PR? (it was closed because of comment in https://github.com/Antonboom/testifylint/pull/2 🤦)
After it should show actual state.

And what about presets question?

2023-09-24 18:05 UTC, ldez commented
I cannot reopen the PR, you are the only one that can do that.