Add new linter canonicalheader
golangci/golangci-lint pull request #4672
Opened 2024-04-22 18:31 UTC by lasiar

[canonicalheader](https://github.com/lasiar/canonicalHeader) analyzes code and reports or fixes non-canonical header key in net/http.Header, [doc](https://pkg.go.dev/net/http#CanonicalHeaderKey).

The linter suggest canonical header:

```go
http.Header{}.Get("Test-Header")
```
instead of non-canonical header:

```go
http.Header{}.Get("TeSt-HeAdEr")
```

This change also speeds up the code a little, benchmark from repo:
```
name             time/op
Canonical-10     29.7ns ± 4%
NonCanonical-10  69.0ns ± 1%

name             alloc/op
Canonical-10      0.00B     
NonCanonical-10   16.0B ± 0%

name             allocs/op
Canonical-10       0.00     
NonCanonical-10    1.00 ± 0%
```

Now, the linter works only with value net/http.Header (not pointer) and with string literal.

----
The reason I created this PR:

I tried to add this linter at https://github.com/golangci/golangci-lint/pull/4241. But the PR was closed, because duplicate linter (https://github.com/golangci/golangci-lint/pull/4241#issuecomment-1853771375).

So this not fully duplicate, [SA1008](https://staticcheck.dev/docs/checks/#SA1008) checks direct write to map.
 `staticcheck` doesn't want to add checks for methods calls https://github.com/dominikh/go-tools/issues/1519#issuecomment-2067816842.

2024-04-22 18:44 UTC, ldez commented
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

- [ ] The CLA must be signed

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description of the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license (AGPL is not allowed) and the file must contain the required information by the license, ex: author, year, etc.
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`.
- [ ] It must not contain `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not modify the AST.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.next.reference.yml`

- [ ] The file `.golangci.next.reference.yml` must be updated.
- [ ] The file `.golangci.reference.yml` must NOT be edited.
- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `lintersdb/builder_linter.go` and `.golangci.next.reference.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
    - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `lintersdb/builder_linter.go`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.
- [ ] `WithURL()` must contain the URL of the repository.

### Recommendations

- [ ] The file `jsonschema/golangci.next.jsonschema.json` should be updated.
- [ ] The file `jsonschema/golangci.jsonschema.json` must NOT be edited.
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

The code review will start after the completion of those checkboxes (except for the specific items that the team will help to verify).

If the author of the PR is a member of the golangci-lint team, he should not edit this message.

**This checklist does not imply that we will accept the linter.**

2024-04-22 19:01 UTC, ldez requested changes

2024-04-22 19:06 UTC, lasiar commented on pkg/golinters/canonicalheader/canonicalheader.go
> +		[]*analysis.Analyzer{canonicalheader.Analyzer},
Thanks for such a quick response!

Done

2024-04-25 22:12 UTC, ldez approved these changes
LGTM

2024-04-25 22:12 UTC, merged