docs: add link on linter without configuration
golangci/golangci-lint pull request #4843
Opened 2024-06-24 16:03 UTC by ldez

Use the same link as the "Back to the top" for linter without configuration.

![Screenshot 2024-06-24 at 18-01-32 Linters golangci-lint](https://github.com/golangci/golangci-lint/assets/5674651/18b44ea9-66ee-49cf-8dc3-41ba5c4ed9ce)

Result:

![Screenshot 2024-06-24 at 18-01-14 Linters golangci-lint](https://github.com/golangci/golangci-lint/assets/5674651/ff1cb0e1-0cf3-4699-b934-60ae8cd14b0e)

link example: `http://localhost:8000/usage/linters/#list-item-asciicheck`

Closes #4842
Fixes #4841

2024-06-26 05:58 UTC, Antonboom requested changes
GitHub icon newlined somewhere
<img width="159" alt="Screenshot 2024-06-26 at 08 54 53" src="https://github.com/golangci/golangci-lint/assets/17127404/5299b578-e927-4cc9-a16c-db243d524587">

"Top" button have underscore
<img width="40" alt="Screenshot 2024-06-26 at 08 55 20" src="https://github.com/golangci/golangci-lint/assets/17127404/57ed76f1-f24f-471c-8266-91e0d171faed">

---

Also, offtop, in contribution guideline need to fix `.reference` to `next.reference`
<img width="800" alt="Screenshot 2024-06-26 at 08 58 03" src="https://github.com/golangci/golangci-lint/assets/17127404/32de28b2-1a15-4935-b4a1-2d104ac23700">

Maybe do it in this PR to not spam issues?

2024-06-26 06:13 UTC, ldez commented
> GitHub icon newlined somewhere

It's just related to the size of the cell, it's expected because it's a table.

> "Top" button have underscore

It's not an underscore but a link "decoration".

2024-06-26 06:35 UTC, ldez commented
I replaced the emoji with an icon.

Before:
![Screenshot 2024-06-26 at 08-34-28 Linters golangci-lint](https://github.com/golangci/golangci-lint/assets/5674651/aff00416-7122-4c4a-8ae7-ace186b24378)

After:
![Screenshot 2024-06-26 at 08-34-18 Linters golangci-lint](https://github.com/golangci/golangci-lint/assets/5674651/04778001-c298-4ba3-a745-f71cfdb3e76c)

2024-06-26 15:37 UTC, alexandear approved these changes

2024-07-01 12:48 UTC, ldez commented
ping @Antonboom

2024-07-03 06:52 UTC, Antonboom approved these changes
> It's just related to the size of the cell,

I just do not realize why we receive different column width in equal sections?

<img width="1052" alt="Screenshot 2024-07-03 at 09 50 50" src="https://github.com/golangci/golangci-lint/assets/17127404/1c873011-3bc4-449d-9490-540efe3691d5">

2024-07-03 11:29 UTC, ldez commented
> I just do not realize why we receive different column width in equal sections?

because it's 2 separated tables.

2024-07-03 11:29 UTC, merged

2024-07-03 11:46 UTC, Antonboom commented
> because it's 2 separated tables.

but why in the second one the description width is shorter? with equal **rem**s

2024-07-03 12:15 UTC, ccoVeille commented
That's why we do backend. Because we have no patience for such mess and nonsense.

I don't understand how frontend can work without becoming insane 😁